version: '3'

services:

  redis:
    image: "redis:alpine"
    container_name: demo_redis
    networks: [main]

  amqp:
    image: "rabbitmq:3"
    container_name: demo_amqp
    networks: [main]

  server:
    build: .
    ports:
      - "8000:8000"
    networks: [main]
    command: ["sh", "/wait-and-run.sh", "/server.sh"]
    env_file: .env

  command-consumer:
    build: .
    networks: [main]
    command: ["sh", "/wait-and-run.sh", "/command-consumer.sh"]
    env_file: .env

networks:
  main: