version: '3'

services:

  driftphp_demo_mysql:
    image: "mysql:8"
    container_name: driftphp_demo_mysql
    networks: [driftphp_demo_main]
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    ports:
      - "3306"

  driftphp_demo_amqp:
    image: "rabbitmq:3-management"
    container_name: driftphp_demo_amqp
    networks: [driftphp_demo_main]
    ports:
      - "5672"
      - "15672"

  driftphp_demo_tiny_balancer:
    image: "driftphp/tiny-balancer"
    container_name: driftphp_tiny_balancer
    ports:
      - "${SERVER_PORT}:8000"
    networks: [driftphp_demo_main]
    entrypoint: ["php", "balancer", "8000", "driftphp_server_1:8000", "driftphp_server_2:8000", "driftphp_server_3:8000"]

  driftphp_demo_server_1:
    build: ..
    networks: [driftphp_demo_main]
    container_name: driftphp_server_1
    entrypoint: ["sh", "/wait-and-run.sh", "/server-entrypoint.sh"]
    env_file: ../.env

  driftphp_demo_server_2:
    build: ..
    networks: [driftphp_demo_main]
    container_name: driftphp_server_2
    entrypoint: ["sh", "/wait-and-run.sh", "/server-entrypoint.sh"]
    env_file: ../.env

  driftphp_demo_server_3:
    build: ..
    networks: [driftphp_demo_main]
    container_name: driftphp_server_3
    entrypoint: ["sh", "/wait-and-run.sh", "/server-entrypoint.sh"]
    env_file: ../.env

  driftphp_demo_websocket:
    build: ..
    networks: [driftphp_demo_main]
    container_name: driftphp_tiny_websocket
    entrypoint: ["sh", "/wait-and-run.sh", "/websocket-entrypoint.sh"]
    ports:
      - "${WEBSOCKET_PORT}:8000"
    env_file: ../.env

networks:
  driftphp_demo_main:
